#pragma once
#include <assert.h>
#include "glm/glm.hpp"
#include <glad/glad.h>
#include <string>
//A class that represents a shader program, manages the loading from disk, compiling and linking of shaders.
//Also manages the uniform attributes of the shader program.
class ShaderProgram
{
public:
	ShaderProgram(std::string vertexShaderPath, std::string fragmentShaderPath);//Compiles and links the shaders.
	ShaderProgram(const ShaderProgram& other) = delete;
	ShaderProgram& operator=(const ShaderProgram& other) = delete;
	~ShaderProgram() noexcept;
	unsigned int GetID() const;	//Returns the shader program ID generated by OpenGL.
public:
	//Define the uniform sending functions using some elegant templating.
	template<typename T>
	void SendUniform(std::string uniformName, const T& value)
	{
		assert(false); //Trying to send an unsupported type.
	}
	//Template specializations.
	template<>
	void SendUniform<glm::mat4>(std::string uniformName, const glm::mat4& value) //Send a matrix of dimension 4.
	{
		glUniformMatrix4fv(GetUniformID(uniformName), 1, GL_FALSE, &value[0][0]);
	}
	template<>
	void SendUniform<glm::mat3>(std::string uniformName, const glm::mat3& value) //Send a matrix of dimension 3
	{
		glUniformMatrix3fv(GetUniformID(uniformName), 1, GL_FALSE, &value[0][0]);
	}
	template<>
	void SendUniform<glm::vec3>(std::string uniformName, const glm::vec3& value) //Send a vector of dimension 3.
	{
		glUniform3fv(GetUniformID(uniformName), 1, &value[0]);
	}
	template<>
	void SendUniform<int>(std::string uniformName, const int& value) //Send an integer.
	{
		glUniform1i(GetUniformID(uniformName), value);
	}
	template<>
	void SendUniform<float>(std::string uniformName, const float& value) //Send a float.
	{
		glUniform1f(GetUniformID(uniformName), value);
	}
private:
	unsigned int GetUniformID(std::string uniformName) const;	//Returns the identifier of the given uniform.
private:
	unsigned int shaderProgramID;
};